run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - revive
    - errcheck
    - unused

issues:
  exclude-dirs:
    - internal/http-server/handlers/url/save/mocks
    - internal/http-server/handlers/url/delete/mocks
    - internal/http-server/handlers/redirect/mocks
